// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BlockedItem {
    "kind": string;
    "value": string;
    "label": string;
    "thumbnail": string;

    /** Creates a new BlockedItem instance. */
    constructor($$source: Partial<BlockedItem> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("thumbnail" in $$source)) {
            this["thumbnail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BlockedItem instance from a string or object.
     */
    static createFrom($$source: any = {}): BlockedItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BlockedItem($$parsedSource as Partial<BlockedItem>);
    }
}

export class SearchPage {
    "results": SearchResult[];
    "cursor": string | null;

    /** Creates a new SearchPage instance. */
    constructor($$source: Partial<SearchPage> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchPage instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new SearchPage($$parsedSource as Partial<SearchPage>);
    }
}

export class SearchResult {
    "id": string;
    "title": string;
    "channel": string;
    "channel_id": string;
    "duration": string;
    "thumbnail": string;
    "published": string;
    "is_short": boolean;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("channel_id" in $$source)) {
            this["channel_id"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = "";
        }
        if (!("thumbnail" in $$source)) {
            this["thumbnail"] = "";
        }
        if (!("published" in $$source)) {
            this["published"] = "";
        }
        if (!("is_short" in $$source)) {
            this["is_short"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class Subscription {
    "channel": string;
    "channel_id": string;
    "avatar": string;

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }
        if (!("channel_id" in $$source)) {
            this["channel_id"] = "";
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}

// Private type creation functions
const $$createType0 = SearchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
