// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BlockChannel(channel: string, channelID: string, thumbnail: string): $CancellablePromise<void> {
    return $Call.ByID(4148008520, channel, channelID, thumbnail);
}

export function BlockVideo(id: string, label: string, thumbnail: string): $CancellablePromise<void> {
    return $Call.ByID(570488384, id, label, thumbnail);
}

export function ListBlocks(): $CancellablePromise<$models.BlockedItem[]> {
    return $Call.ByID(2557045230).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListSubscriptions(): $CancellablePromise<$models.Subscription[]> {
    return $Call.ByID(499179062).then(($result: any) => {
        return $$createType3($result);
    });
}

export function LoadChannelVideos(channel: string, channelID: string): $CancellablePromise<$models.SearchPage> {
    return $Call.ByID(4210554387, channel, channelID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function LoadHome(): $CancellablePromise<$models.SearchPage> {
    return $Call.ByID(1607334939).then(($result: any) => {
        return $$createType4($result);
    });
}

export function LoadShorts(): $CancellablePromise<$models.SearchPage> {
    return $Call.ByID(1129783071).then(($result: any) => {
        return $$createType4($result);
    });
}

export function LoadShortsMore(videoID: string): $CancellablePromise<$models.SearchPage> {
    return $Call.ByID(1957907658, videoID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function LoadSubscriptionAvatar(channel: string, channelID: string): $CancellablePromise<string> {
    return $Call.ByID(415297140, channel, channelID);
}

export function SearchYouTube(query: string): $CancellablePromise<$models.SearchPage> {
    return $Call.ByID(1189253453, query).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SearchYouTubeMore(cursor: string): $CancellablePromise<$models.SearchPage> {
    return $Call.ByID(804175784, cursor).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetInputLock(locked: boolean): $CancellablePromise<void> {
    return $Call.ByID(1855026155, locked);
}

export function SubscribeChannel(channel: string, channelID: string, avatar: string): $CancellablePromise<void> {
    return $Call.ByID(1834939763, channel, channelID, avatar);
}

export function UnblockItem(item: $models.BlockedItem): $CancellablePromise<void> {
    return $Call.ByID(3563390515, item);
}

export function UnsubscribeChannel(channel: string): $CancellablePromise<void> {
    return $Call.ByID(1845182636, channel);
}

// Private type creation functions
const $$createType0 = $models.BlockedItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Subscription.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SearchPage.createFrom;
